#!/bin/bash

# $1 project file name
# $2 ssh server's ip


if [ $# != 2 ]; then
	echo first param is Project name, second param is ssh server\'s ip.
	exit 1
fi

[ ${0:0:1} = / ] && c_dir=${0%/*} || c_dir=$PWD/${0%/*}
#echo current dir is: $c_dir
localDylibPath=$c_dir/Package/Library/MobileSubstrate/DynamicLibraries/$1.dylib
localPListPath=$c_dir/Package/Library/MobileSubstrate/DynamicLibraries/$1.plist
#echo $localDylibPath
#echo $localPListPath

serverDylibPath=root@$2:/Library/MobileSubstrate/DynamicLibraries/$1.dylib
serverPListPath=root@$2:/Library/MobileSubstrate/DynamicLibraries/$1.plist

scp $localDylibPath $serverDylibPath
scp $localPListPath $serverPListPath

ssh root@$2 chmod +x /Library/MobileSubstrate/DynamicLibraries/$1.dylib

ssh root@$2 killall SpringBoard


