
platform :ios, '8.0'

use_frameworks!

source "https://github.com/CocoaPods/Old-Specs"

target 'singleview2' do


  pod 'ReactiveObjC', '2.0.0'
  # pod 'ReactiveCocoa', '~> 5.0.0'

  pod 'Masonry', '1.0.2'

  pod 'RegexKitLite', '4.0'

  pod 'YYText', '1.0.7'

end
