#!/bin/bash

# $1 ssh server's ip


if [ $# != 1 ]; then
	echo first param is ssh server\'s ip.
	exit 1
fi

[ ${0:0:1} = / ] && c_dir=${0%/*} || c_dir=$PWD/${0%/*}
#echo $c_dir
#projname= basename $c_dir
#echo $projname
#exit 1

projectName=kanpod

#echo current dir is: $c_dir
localDylibPath=$c_dir/Package/Library/MobileSubstrate/DynamicLibraries/$projectName.dylib
localPListPath=$c_dir/Package/Library/MobileSubstrate/DynamicLibraries/$projectName.plist
#echo $localDylibPath
#echo $localPListPath

serverDylibPath=root@$1:/Library/MobileSubstrate/DynamicLibraries/$projectName.dylib
serverPListPath=root@$1:/Library/MobileSubstrate/DynamicLibraries/$projectName.plist

scp $localDylibPath $serverDylibPath
if [ $? != 0 ]; then
	exit 2;
fi

scp $localPListPath $serverPListPath
if [ $? != 0 ]; then
	exit 3 ;
fi

ssh root@$1 chmod +x /Library/MobileSubstrate/DynamicLibraries/$projectName.dylib
if [ $? != 0 ]; then
	exit 4;
fi

ssh root@$1 killall SpringBoard



